server:
  port: 5000

app:
  app-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.app-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: notification_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.app-prefix}/notify/**
          filters:
            - StripPrefix=2

        - id: exam_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.app-prefix}/exam/**
          filters:
            - StripPrefix=2
        - id: chat_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.app-prefix}/chat/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.app-prefix}/file/**
          filters:
            - StripPrefix=2