server:
  port: 8085
  servlet:
    context-path: /file
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://root1:root@cluster0.4pjx8.mongodb.net/file_service


app:
  services:
    identity: http://localhost:8080/identity
    exam: http://localhost:8082/exam