server:
  port: 8081
  servlet:
    context-path: /notify
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/notification_service'
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
config:
  mail:
    host: smtp.gmail.com
    port: 587
    username: phancongtu25032002@gmail.com
    password: udvepsndgybmyzye
send-by-mail:
  verification-code-time: 30 #minutes
  reset-password-code-time: 15 #minutes

app:
  services:
    identity: http://localhost:8080/identity
